name: Format

on:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: '--dry-run --set-exit-if-changed'
          skipCommit: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
