name: format

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: '--dry-run --set-exit-if-changed'
          skipCommit: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
