name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test
        if: startsWith(github.ref , 'refs/tags/') != true
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
          STREAM_SECRET: ${{ secrets.STREAM_SECRET }}
        run: |
          ./gradlew spotlessCheck --no-daemon
          ./gradlew test --no-daemon
