name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8']
        gradle: ['6.2']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Set up Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew test --no-daemon -Dsnom.test.functional.gradle=${{ matrix.gradle }}
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
          STREAM_SECRET: ${{ secrets.STREAM_SECRET }}
