name: javadoc
on:
  push:
    branches:
      - main
jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Generate doc
        run: ./gradlew --no-daemon javadoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs/javadoc/
