name: javadoc
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Node.js 16
        uses: actions/setup-node@v6
        with:
          node-version: 16
      - name: Generate doc
        run: ./gradlew --no-daemon javadoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/docs/javadoc/
